version: "4"
services:
    ## MySQL
    mysql:
        image: mysql
        container_name: mysqldb
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        restart: always
        ports:
            - "3316:3306"
        expose:
            - "3316"
        volumes:
            - ./mysql-data:/var/lib/mysql
volumes:
    mysql-data:
